version: "3"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "2222:2222"
    networks:
      - mern-network
    # depends_on:
    #   - mongo
    # environment:
    #   - MONGODB_URI=mongodb://mongo:27017/your-database-name

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    networks:
      - mern-network
    # depends_on:
    #   - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern-network
    # volumes:
    #   - mongo-data:/data/db
    # environment:
    #   - MONGO_INITDB_DATABASE=your-database-name

networks:
  mern-network:
    driver: bridge
# volumes:
#   mongo-data:
